version: '3'
services:
  react-app:
    # for -it flag in the terminal
    # stdin_open: true 
    # tty: true 
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Akshay Sood PROD
    ports:
      - 8080:80
    # env_file: # to include .env file for env vars
    #   - ./.env