version: '3'
services:
  react-app:
    # for -it flag in the terminal
    # stdin_open: true 
    # tty: true 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - REACT_APP_NAME=Akshay Sood DEV
      # below is for hot reloading
      - WATCHPACK_POLLING=true 
    # env_file: # to include .env file for env vars
    #   - ./.env
    volumes:
      - ./src:/app/src:ro