version: '3'
services:
  react-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - REACT_APP_NAME=Akshay Sood
      - WATCHPACK_POLLING=true
    # env_file: # to include .env file for env vars
    #   - ./.env
    volumes:
      - ./src:/app/src:ro